### ISSUE TITLE
Content plugin for JoomGallery

### ISSUE THREAD

**Issue by mastervanleeuwen** [JoomGalleryfriends/JG4-dev#329]
Hi all,

First of all: thank you for working on a new version of JoomGallery for Joomla 4. 

I maintain a website where I have been using joomgallery together with the content plugin (which allows to show pictures and category views from JoomGallery in articles and other components). I have written a base version of the joomgallery plugin for Joomla 4 that works with the new Joomla 4 version of JoomGallery. You can find the code here:

https://github.com/mastervanleeuwen/JoomGalleryPlugin

and a minimalistic test site here: https://jtrackgalleryj4.gta-trek.eu/index.php/en/joomgallery-plugin

I hope this is of use to the community. I would be happy if this could become part of the JoomGallery code that is maintained by you.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Alwin,

Thanks for your interest and for giving the plugin a try. What error message do you get? I have tested the plugin and it worked for me, but it is possible that I forgot to commit a file or so.

I use:
`zip -r ../plg_joomgallery.zip *`

to make a zip archive of the plugin and it includes these files:
```
  adding: LICENSE (deflated 66%)
  adding: README.md (deflated 34%)
  adding: joomgalleryplugin.xml (deflated 52%)
  adding: language/ (stored 0%)
  adding: language/en-GB/ (stored 0%)
  adding: language/en-GB/plg_content_joomgallery.sys.ini (deflated 24%)
  adding: language/en-GB/plg_content_joomgallery.ini (deflated 25%)
  adding: services/ (stored 0%)
  adding: services/provider.php (deflated 64%)
  adding: src/ (stored 0%)
  adding: src/Extension/ (stored 0%)
  adding: src/Extension/JoomGalleryPlugin.php (deflated 71%)
```

**Comment by mastervanleeuwen** [comment]
Hi Alwin,

Good catch; line 9 is incorrect; I must have introduced it accidentally when cleaning up the manifest file. I have fixed this in the repository. 

You can try reinstalling, but on my system that was not enough, and I also could not uninstall the plugin the normal way because when I going to 'Manage Extensions' in the System menu gave the same error. I had to remove the JoomGalleryPlugin item from the 'extensions' table in the data base by hand (using phpmyadmin). Let me know if you run into this problem as well and need help with fixing this. Sorry for the inconvenience.

This version of the plugin has no configuration parameters; the settings are taken from the joomgallery component.

Note that there is also a recent post on the JoomGallery forum: https://www.forum.joomgalleryfriends.net/forum/index.php?thread/384-joomplu-plugin/&postID=2484#post2484 with a new version of the JoomPlu plugin. I only became aware of this after writing my version and have not tested it yet. It may be closer in functionality to the JoomPlu plugin for Joomla 3.

Best regards,

Marco.

**Comment by Elfangor93** [comment]
`<namespace path="src">My\Plugin\Content\Joomgallery</namespace>`

I recommend you to use a more unique string than `My` in the namespace of your Plugin.

Having a class name with upper case letters in between like you do with `JoomGalleryPlugin` is dangerous. It is possible but it can lead to problems as Windows is case insensitive and Linux based systems are case sensitive. This means that a setup can work on a Windows machine but may break on a Linux machine.

`Class "My\Plugin\Content\Joomgallery\Extension\JoomGalleryPlugin" not found`

If a newly installed extension throws this error, it might be that Joomla hasen't updated its namespace index correctly. Sometimes it resolves the problem by deleteing the file `/administrator/cache/autoload_psr4.php` and then reload the page.

**Comment by MrMusic** [comment]
>I had to remove the JoomGalleryPlugin item from the 'extensions' table in the data base by hand (using phpmyadmin).

I have deleted the joomgallery folder in plugins/content. Then the plugin can be 'uninstalled'.

Now wanted to test the new version. Unfortunately I still get the same error:
```
0 Class "My\Plugin\Content\Joomgallery\Extension\JoomGalleryPlugin" not found 

Call stack
# 	Function 	Location
1 	() 	JROOT\plugins\content\joomgallery\services\provider.php:23
2 	Joomla\DI\ServiceProviderInterface@anonymousC:\xampp8_2_4\htdocs\vocalitas\plugins\content\joomgallery\services\provider.php:11$2250->{closure}() 	JROOT\libraries\vendor\joomla\di\src\ContainerResource.php:182
3 	Joomla\DI\ContainerResource->getInstance() 	JROOT\libraries\vendor\joomla\di\src\Container.php:96
4 	Joomla\DI\Container->get() 	JROOT\libraries\src\Extension\ExtensionManagerTrait.php:177
5 	Joomla\CMS\Application\CMSApplication->loadExtension() 	JROOT\libraries\src\Extension\ExtensionManagerTrait.php:99 
```

**Comment by MrMusic** [comment]
Hi Marco,
yes, installation and uninstallation works fine now. Thank you.
I have now tested it with Joomla 4 and JG 4.0.0-beta1 and it works fine.
With Joomla 5.2.3 the following error appears in the frontend:
```
0 There is no "com_joomgallery.joomgrid" asset of a "script" type in the registry. 

Call Stack
# 	Function 	Location
1 	() 	JROOT\libraries\src\WebAsset\WebAssetRegistry.php:135
2 	Joomla\CMS\WebAsset\WebAssetRegistry->get() 	JROOT\libraries\src\WebAsset\WebAssetManager.php:274
3 	Joomla\CMS\WebAsset\WebAssetManager->useAsset() 	JROOT\libraries\src\WebAsset\WebAssetManager.php:208
4 	Joomla\CMS\WebAsset\WebAssetManager->__call() 	JROOT\plugins\content\joomgallery\src\Extension\JoomGalleryPlugin.php:195
5 	My\Plugin\Content\Joomgallery\Extension\JoomGalleryPlugin->renderCat() 	JROOT\plugins\content\joomgallery\src\Extension\JoomGalleryPlugin.php:266 
```
Is the plugin not yet compatible with Joomla 5?

**Comment by mastervanleeuwen** [comment]
I see. I had used a recent master version of  JoomGallery to finalise the code and it seems that this commit from 2 weeks ago:
https://github.com/JoomGalleryfriends/JG4-dev/commit/0238057f6f53e7bd0fab5b65b86eb3a29779ae25
is needed to make the plugin work as is. I could make a temporary patch for the plugin, but it may be better to either take a more recent version of joomgallery, or to wait until the next (beta?) release?

I don't expect this to depend on the Joomla version. I used Joomla 5 for development.

Best regards, Marco.
